import { t, type Locale } from '@/i18n/utils';
import type { TapAppLabels } from '@/components/tool/TapApp';

export function tapLabels(locale: Locale): TapAppLabels {
  return {
    tapCta: t(locale, 'tap.cta'),
    tapHint: t(locale, 'tap.hint'),
    placeholder: t(locale, 'tap.placeholder'),
    unit: t(locale, 'tap.unit'),
    confidenceNone: t(locale, 'confidence.none'),
    confidenceLow: t(locale, 'confidence.low'),
    confidenceMedium: t(locale, 'confidence.medium'),
    confidenceHigh: t(locale, 'confidence.high'),
    confidenceShared: t(locale, 'confidence.shared'),
    confidenceManual: t(locale, 'confidence.manual'),
    enterBpm: t(locale, 'tap.enterBpm'),
    reset: t(locale, 'control.reset'),
    half: t(locale, 'control.half'),
    double: t(locale, 'control.double'),
    copy: t(locale, 'control.copy'),
    copied: t(locale, 'control.copied'),
    copyFail: t(locale, 'control.copyFail'),
    share: t(locale, 'control.share'),
    fullscreen: t(locale, 'control.fullscreen'),
    exitFullscreen: t(locale, 'control.exitFullscreen'),
    metronomeStart: t(locale, 'control.metronomeStart'),
    metronomeStop: t(locale, 'control.metronomeStop'),
    meterLabel: t(locale, 'meter.label'),
    accentHint: t(locale, 'meter.accentHint'),
    delayTitle: t(locale, 'panel.delay'),
    historyTitle: t(locale, 'panel.history'),
    historyEmpty: t(locale, 'panel.historyEmpty'),
    favoritesTitle: t(locale, 'favorites.title'),
    favoritesAdd: t(locale, 'favorites.add'),
    favoritesSaved: t(locale, 'favorites.saved'),
    favoritesEmpty: t(locale, 'favorites.empty'),
    favoritesEdit: t(locale, 'favorites.edit'),
    favoritesDone: t(locale, 'favorites.done'),
    favoritesRemove: t(locale, 'favorites.remove'),
    favoritesSaveEdit: t(locale, 'favorites.saveEdit'),
    favoritesBpm: t(locale, 'favorites.bpm'),
    favoritesMeter: t(locale, 'favorites.meter'),
    favoritesManageHint: t(locale, 'favorites.manageHint'),
    genreHintTitle: t(locale, 'genreHint.title'),
    genreClosest: t(locale, 'genreHint.closest'),
    outOfRange: t(locale, 'outofrange'),
    noteLabels: {
      'note.whole': t(locale, 'note.whole'),
      'note.half': t(locale, 'note.half'),
      'note.quarter': t(locale, 'note.quarter'),
      'note.eighth': t(locale, 'note.eighth'),
      'note.sixteenth': t(locale, 'note.sixteenth'),
      'note.whole.dotted': t(locale, 'note.whole.dotted'),
      'note.half.dotted': t(locale, 'note.half.dotted'),
      'note.quarter.dotted': t(locale, 'note.quarter.dotted'),
      'note.eighth.dotted': t(locale, 'note.eighth.dotted'),
      'note.sixteenth.dotted': t(locale, 'note.sixteenth.dotted'),
      'note.whole.triplet': t(locale, 'note.whole.triplet'),
      'note.half.triplet': t(locale, 'note.half.triplet'),
      'note.quarter.triplet': t(locale, 'note.quarter.triplet'),
      'note.eighth.triplet': t(locale, 'note.eighth.triplet'),
      'note.sixteenth.triplet': t(locale, 'note.sixteenth.triplet'),
    },
  };
}
